ADD general.py
BigDataBiology/argNorm pull request #28
Opened 2024-04-02 00:33 UTC by Vedanth-Ramji

Making argNorm better suited as a library. 

- Providing a separate `map_to_aro` function so argNorm can be used without the `normalizers`
- Separated `get_aro_mapping_table` function from `BaseNormalizer` so it can be used independently

2024-04-02 01:58 UTC, luispedro commented on argnorm/normalizers.py
> +        return ref_genes.apply(process_funcs_by_db[self.database])
Is this needed?

2024-04-02 02:01 UTC, luispedro commented on argnorm/general.py
> +    except:
Naked `except` is not good

2024-04-02 02:03 UTC, luispedro requested changes
I'm not sure about splitting to `general`. Is the goal that people import it as 

```python
from argnorm import general
```

?

Also, tests are needed

2024-04-02 04:44 UTC, Vedanth-Ramji commented
Yes, well now that I have renamed it to 'lib' it should be something like: `from argnorm import lib` or `from argnorm.lib import *`. 

Is that ok?

2024-04-10 03:51 UTC, luispedro requested changes

2024-04-10 03:51 UTC, luispedro commented on argnorm/normalizers.py
> +from .lib import *
Please avoid the `import *`

2024-04-10 10:18 UTC, luispedro commented
Can you some notes to the Changelog about this?

2024-04-15 05:34 UTC, luispedro approved these changes

2024-04-15 05:34 UTC, merged