ADD: cluster and reverse complement correction for resfinder
BigDataBiology/argNorm pull request #38
Opened 2024-04-21 09:44 UTC by Vedanth-Ramji

- Resfinder has gene clusters which can't be passed through RGI using 'contig' mode.
- Gene clusters were identified and were manually assigned ARO numbers.
- A seperate file with manual curation for gene clusters and RCs was created, and their AROs were updated after concatenating RGI results and genes not in RGI results.
- 40 gene clusters present.
- 4 genes in reverse complement form also present. blaBIM-1_1_CP016446 and mph(D)_1_AB048591 were not found in CARD and were given parent ARO mappings. RGI correctly assigned ARO numbers to other two.
- Corrected erm(X)_1_M36726 ARO mapping
- Delete get_data_path function

2024-04-21 10:00 UTC, luispedro reviewed
Thanks.

It seems, however, that this could have been done without special-casing `resfinder`? Why is this different from the other manual curation files?

2024-04-21 10:00 UTC, luispedro commented on argnorm/data/cluster_rc_correction/notes.md
> +- A seperate file with manual curation for gene clusters and RCs was created, and their AROs were updated after concatenating RGI results and genes not in RGI results.
s/seperate/separate/

2024-04-21 10:04 UTC, luispedro commented
The code for actually running rgi correctly for resfinder is still missing as well.

2024-04-22 08:55 UTC, Vedanth-Ramji commented
I just added the code for using the AA version of resfinder.

> It seems, however, that this could have been done without special-casing `resfinder`? Why is this different from the other manual curation files?

The other manual curation files are adding genes that are not present in the mapping tables (i.e. RGI can't map them automatically). The new 'correction' files are changing mappings that are already present in the mapping tables (i.e. correcting RGI as it is not detecting a gene cluster or reverse complement properly and mapping to a wrong ARO number).

2024-04-22 10:32 UTC, luispedro commented
> The other manual curation files are adding genes that are not present in the mapping tables (i.e. RGI can't map them automatically). The new 'correction' files are changing mappings that are already present in the mapping tables (i.e. correcting RGI as it is not detecting a gene cluster or reverse complement properly and mapping to a wrong ARO number).

I know this, but I don't see why it matters for my question. Why does the code need to special-case `resfinder`? Isn't this just a different way in which the files were generated, but the same code can handle both.

2024-04-22 10:33 UTC, luispedro requested changes

2024-04-22 10:33 UTC, luispedro commented on db_harmonisation/crude_db_harmonisation.py
> +    ofile = f'./dbs/resfinder.faa'
This should not be hardcoded, but

```python
ofile = ifile.replace('.fna', '.faa')
```

2024-04-25 00:26 UTC, luispedro commented on argnorm/lib.py
> +    if database != 'resfinder':
Can we remove this `if` statement?

2024-04-25 00:27 UTC, luispedro commented on argnorm/lib.py
> +    aro_mapping_table = df
We can avoid this by not having an intermediate object called `df`

2024-04-25 00:28 UTC, luispedro requested changes
I still want to remove the special casing of `resfinder`

2024-04-25 10:33 UTC, merged