Update cli.py
BigDataBiology/argNorm pull request #43
Opened 2024-05-09 18:39 UTC by sebastianLedzianowski

argNorm accepts input regardless of case (on the command line)

2024-05-09 22:33 UTC, luispedro commented on argnorm/cli.py
> +    parser.add_argument('-i', '--input', type=str.lower,
This should not be `str.lower`, though. It's a filename and should be passed as is, no?

2024-05-09 22:33 UTC, luispedro commented on argnorm/cli.py
> +    parser.add_argument('-o', '--output', type=str.lower,
Same as above

2024-05-09 22:34 UTC, luispedro requested changes
See the comments about `str.lower`

Also, please add some tests inside `integration_tests/run_argnorm.py`

2024-05-09 22:35 UTC, luispedro commented
Thanks a lot for the effort. I actually was not aware that you could pass `str.lower` to `argparse`, that's pretty nice. But I think it should not apply to the `-i`/`-o` arguments

2024-05-11 10:58 UTC, sebastianLedzianowski commented
Edited as directed. I hope everything is fine now.

2024-05-11 11:02 UTC, luispedro commented on integration_tests/run_argnorm.py
>      file = f'abricate.{db}.tsv'
This should now be

```python
    file  = f'abricate.{db.lower()}.tsv'
```

2024-05-11 11:02 UTC, luispedro requested changes
Tests are failing, but I think it's a trivial thing (see line comment).

Other than that, it could be merged!

2024-05-11 11:15 UTC, merged

2024-05-11 11:16 UTC, luispedro commented
Thanks! Merged. This is much appreciated!

@Vedanth-Ramji : can you make a note in the `CHANGELOG` and docs about this change and credit @sebastianLedzianowski ?