ADD groot normalizer
BigDataBiology/argNorm pull request #60
Opened 2024-07-27 18:34 UTC by Vedanth-Ramji

2024-08-03 07:30 UTC, Vedanth-Ramji commented
I've marked this as ready for review now as the normalizer is out. Once #61 is merged, I'll go ahead and add the tests for groot

2024-08-03 23:01 UTC, luispedro commented
There are several unanswered comments (I just added a few more)

2024-08-04 04:07 UTC, Vedanth-Ramji commented
Oh, could you please let me know where I could find these comments? I can't find them in my mail or on GitHub.

2024-08-04 04:39 UTC, luispedro requested changes

2024-08-04 06:22 UTC, Vedanth-Ramji commented on db_harmonisation/README.md
> +Groot uses `resfinder`, `CARD`, and `argannot`. However, the versions of `argannot` and `resfinder` used are much older than the default `argannot` and `resfinder`. `CARD` always points to the latest
The `groot` documentations says that the latest versions of `card`, `argannot`, and `resfinder` are used to create the `groot db`, however, when I took a look at the [code to generate the `groot-db`](https://[raw.githubusercontent.com/will-rowe/groot/master/db/groot-database/make-groot-dbs.sh](https://raw.githubusercontent.com/will-rowe/groot/master/db/groot-database/make-groot-dbs.sh)), I found that only the latest version of the CARD database is downloaded, while older versions of resfinder and argannot (v3) are used - these were the latest versions of `resfinder` and `argannot` when the groot documentation was written.

2024-08-04 07:23 UTC, luispedro commented
Thanks. I think this context is not clear from the proposed documentation text.

2024-08-04 07:45 UTC, Vedanth-Ramji commented
I just updated the readme for db_harmonisation now. Is it ok now?

2024-08-13 04:13 UTC, merged