DOC add documentation on output formats
BigDataBiology/argNorm pull request #70
Opened 2024-10-07 14:31 UTC by Vedanth-Ramji

Added a table to the documentation detailing the columns that argNorm adds to ARG annotation tools' outputs. Also mentioned how argNorm displays the software version used in the output tsv files.

2024-10-08 00:05 UTC, luispedro requested changes

2024-10-08 00:05 UTC, luispedro commented on docs/index.md
> +A comment is added to the very top of the ARG annotation tool outputs specifying the argNorm version used. For example: '# argNorm version: 0.6.0'
Explicitly mention that "Lines starting with `#` should be considered comments and ignored"

2024-10-10 10:39 UTC, Vedanth-Ramji commented
Hello @luispedro are there any other comments you would like me to address in the PR?

2024-10-10 11:10 UTC, luispedro approved these changes

2024-10-10 11:10 UTC, merged